### ISSUE TITLE
Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by snorreks** [studds/nx-aws#100]
This is not working on nx 13, i get the following error:

```console
> nx run mailvideo-sam:build

Running build for entry src\lambdas\hello
Cannot convert undefined or null to object

 ———————————————————————————————————————————————————————————

 >  NX   Running target "mailvideo-sam:build" failed

   Failed tasks:

   - mailvideo-sam:build

   Hint: run the command with --verbose for more details.

   See Nx Cloud run details at https://nx.app/runs/Y0aUShC9QjB

 ELIFECYCLE  Command failed with exit code 1.
```
### build config
```json
{
	"root": "apps/mailvideo/sam",
	"sourceRoot": "apps/mailvideo/sam/src",
	"projectType": "application",
	"targets": {
		"build": {
			"builder": "@nx-aws/sam:build",
			"options": {
				"outputPath": "dist/apps/mailvideo/sam",
				"template": "apps/mailvideo/sam/template.yaml",
				"tsConfig": "apps/mailvideo/sam/tsconfig.app.json",
				"sourceMap": true,
				"maxWorkers": 1
			},
			"configurations": {
				"production": {
					"optimization": true,
					"extractLicenses": true,
					"inspect": false,
					"fileReplacements": [
						{
							"replace": "apps/mailvideo/sam/src/env/env.ts",
							"with": "apps/mailvideo/sam/src/env/env.prod.ts"
						}
					]
				}
			}
		},
		...
```
### src/lambdas/hello.ts
```ts
import type { APIGatewayProxyHandler } from 'aws-lambda';

/**
 * A simple example to return payload: 'hello'.
 * @param event {APIGatewayProxyEvent} event - The event passed to the handler.
 */
export const handler: APIGatewayProxyHandler = async () => {
	return {
		body: JSON.stringify({ payload: 'hello' }),
		statusCode: 200,
	};
};
```
### template.yaml
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend for nx-aws-example

Globals:
    Function:
        Runtime: nodejs14.x
        Timeout: 5
        MemorySize: 128

Resources:
    Hello:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambdas
            Handler: hello.handler

```

### NX Report
```console
   Node : 16.13.2
   OS   : win32 x64
   pnpm : 6.31.0

   nx : 13.7.2
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.2
   @nrwl/cypress : 13.7.2
   @nrwl/detox : undefined
   @nrwl/devkit : 12.10.1
   @nrwl/eslint-plugin-nx : 13.7.2
   @nrwl/express : undefined
   @nrwl/jest : 13.7.2
   @nrwl/js : 13.7.3
   @nrwl/linter : 13.7.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 12.10.1
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.2
   @nrwl/tao : 13.7.2
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.3
   typescript : 4.5.5
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
         @nx-aws/sam: 0.12.2
```
