### ISSUE TITLE
@nx-aws/sam: Generated WebBucketPolicy is invalid

### ISSUE THREAD

**Issue by studds** [studds/nx-aws#66]
We generate:

```
  # Policy to allow CF to access the private webbucket
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub '${WebBucket.Arn}/*'
```

Should be:

```yaml
  # Policy to allow CF to access the private webbucket
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginIdentity.S3CanonicalUserId
            Action:
              - 's3:GetObject'
              # ListBucket is required so that a 404 is returned on misses
              - 's3:ListBucket'
            Resource:
              - !Sub '${WebBucket.Arn}/*'
              - !Sub '${WebBucket.Arn}'
```
