### ISSUE TITLE
Best place for SAM parameters

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#75]
In my main API template file, I have added some parameters for the domain name and SSL certificate which I need manually created. 

My app is going to have multiple domains, dev, prod + 1 domain per developer. 

Where do you think the best place to set these values is. 

1. somewhere in AWS. 
2. In workspace.json as a configuration (what I am leaning towards)
3. In some other file SAM TOML file ?

```
Parameters:
  Domain:
    Description: Domain name
    Type: String
    Default: dev.foo.com
  DomainSSLCertificateARN:
    Description: Domain name SSL certificate
    Type: String
    Default: arn:aws:acm:us-east-1:938175342066:certificate/sgsfdfgfsdgdfg
```

The main reason I am asking is the configurations maybe will get a bit large when every developer needs an entry. Still this might be the best place.
